const express = require('express');
const router = express.Router();
const authRoutes = require('./authRoutes');
const donationRoutes = require('./donationRoutes');
const campaignRoutes = require('./campaignRoutes');
const initiativeRoutes = require('./initiativeRoutes');
const workRoutes = require('./workRoutes');
const storyRoutes = require('./storyRoutes');
const galleryRoutes = require('./galleryRoutes');
const impactRoutes = require('./impactRoutes');
const teamRoutes = require('./teamRoutes');
const testimonialRoutes = require('./testimonialRoutes');
const documentRoutes = require('./documentRoutes');
const volunteerRoutes = require('./volunteerRoutes');
const enquiryRoutes = require('./enquiryRoutes');
const siteContentRoutes = require('./siteContentRoutes');
const settingsRoutes = require('./settingsRoutes');
const notificationRoutes = require('./notificationRoutes');
const mediaRoutes = require('./mediaRoutes');
const adminRoutes = require('./adminRoutes');

router.use('/auth', authRoutes);
router.use('/donations', donationRoutes);
router.use('/campaigns', campaignRoutes);
router.use('/initiatives', initiativeRoutes);
router.use('/work', workRoutes);
router.use('/stories', storyRoutes);
router.use('/gallery', galleryRoutes);
router.use('/impact', impactRoutes);
router.use('/team', teamRoutes);
router.use('/testimonials', testimonialRoutes);
router.use('/documents', documentRoutes);
router.use('/volunteers', volunteerRoutes);
router.use('/enquiries', enquiryRoutes);
router.use('/content', siteContentRoutes);
router.use('/settings', settingsRoutes);
router.use('/notifications', notificationRoutes);
router.use('/media', mediaRoutes);
router.use('/admin', adminRoutes);

module.exports = router;
