const mongoose = require('mongoose');

const siteSettingsSchema = new mongoose.Schema({
  foundationName: { type: String, default: 'Jadu & Art Foundation' },
  logo: { type: String, default: '/logo.svg' },
  darkLogo: { type: String, default: '/logo-horizontal.svg' },
  favicon: { type: String, default: '/favicon.svg' },
  metaTitle: { type: String, default: 'Jadu & Art Foundation | Seva • Sanskar • Samriddh Bharat' },
  metaDescription: { type: String, default: 'Jadu & Art Foundation works towards education, healthcare, cow welfare and humanitarian support while promoting values of service, humanity and a better future for India.' },
  metaKeywords: { type: String, default: 'Jadu and Art, NGO, Social Impact, Education, Healthcare, Cow Welfare, Charity, India' },
  ogImage: { type: String, default: '/logo.svg' },
  siteUrl: { type: String, default: 'https://jaduandart.org' },
  twitterHandle: { type: String, default: '@jaduandart' },
  facebookUrl: { type: String, default: '' },
  instagramUrl: { type: String, default: '' },
  youtubeUrl: { type: String, default: '' },
  linkedinUrl: { type: String, default: '' },
  whatsappNumber: { type: String, default: '' },
  author: { type: String, default: 'Jadu & Art Foundation' },
  googleAnalyticsId: { type: String, default: '' },
  googleSearchConsoleVerification: { type: String, default: '' },
  officialEmail: { type: String, default: 'jaduandartfoundation@gmail.com' },
  primaryGreen: { type: String, default: '#006B3C' },
  darkTeal: { type: String, default: '#063F36' },
  orange: { type: String, default: '#F47B20' },
  gold: { type: String, default: '#C99020' },
  background: { type: String, default: '#FFFFFF' },
  creamBackground: { type: String, default: '#FBF8F1' },
  textPrimary: { type: String, default: '#17201D' },
  textSecondary: { type: String, default: '#5F6B66' },
  border: { type: String, default: '#E4E9E5' },
  tagline: { type: String, default: 'Spiritual Values | Social Impact | A Brighter India' },
  hindiTagline: { type: String, default: 'Seva • Sanskar • Samriddh Bharat' },
  defaultLanguage: { type: String, default: 'en' },
  currency: { type: String, default: 'INR' },
  timezone: { type: String, default: 'Asia/Kolkata' },
  maintenanceMode: { type: Boolean, default: false },
  visibleSections: {
    heroSection: { type: Boolean, default: true },
    impactStrip: { type: Boolean, default: true },
    aboutSection: { type: Boolean, default: true },
    initiativesSection: { type: Boolean, default: true },
    workSection: { type: Boolean, default: true },
    founderSection: { type: Boolean, default: true },
    lifePhilosophySection: { type: Boolean, default: true },
    futureGenerationsSection: { type: Boolean, default: true },
    humanitySection: { type: Boolean, default: true },
    storiesSection: { type: Boolean, default: true },
    gallerySection: { type: Boolean, default: true },
    testimonialsSection: { type: Boolean, default: true },
    volunteerSection: { type: Boolean, default: true }
  },
  donationPopup: {
    enabled: { type: Boolean, default: true },
    title: { type: String, default: 'DONATE NOW' },
    hindiTitle: { type: String, default: 'आपका सहयोग महत्वपूर्ण है' },
    description: { type: String, default: 'Your contribution can help us continue serving people, communities and animals in need.' },
    image: { type: String, default: 'https://images.pexels.com/photos/1183434/pexels-photo-1183434.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2' },
    buttonText: { type: String, default: 'DONATE NOW' },
    delay: { type: Number, default: 10000 },
    cooldown: { type: Number, default: 604800000 },
    defaultAmount: { type: Number, default: 1000 }
  },
  // Organization & Legal Information Details
  legalContactEmail: { type: String, default: 'jaduandartfoundation@gmail.com' },
  lastUpdatedDate: { type: String, default: 'September 26, 2026' },
  registeredAddress: { type: String, default: '[Registered Office Address to be added]' },
  registrationType: { type: String, default: '[Registration Type to be added]' },
  registrationNumber: { type: String, default: '[Registration Number to be added]' },
  pan: { type: String, default: '[PAN to be added]' },
  status12A: { type: String, default: '[12A Status to be added]' },
  status80G: { type: String, default: '[80G Status to be added]' },
  fcraStatus: { type: String, default: '[FCRA Status to be added]' },
  otherRegistrations: { type: String, default: '[Other verified registrations to be added]' },
  privacyPolicyCustomText: { type: String, default: '' },
  termsCustomText: { type: String, default: '' },
  refundPolicyCustomText: { type: String, default: '' }
}, { timestamps: true });

module.exports = mongoose.model('SiteSettings', siteSettingsSchema);
